### ISSUE TITLE
no correct COM port available in settings

### ISSUE THREAD

**Issue by michal2229** [GeoNomad/LuaLoader#3]
Hello,
I have following problem: I want to send some commands to my ESP from PC trough LuaLoader, but I can't see my FTDI COM port in settings (it is COM16). I have only choice between COM2 and COM4. 
Everything works fine on PetesSerialTerminal though (http://tech.scargill.net/the-simple-serial-terminal-revisited/). 
How can I fix it?

Thanks in advance.

**Comment by GeoNomad** [comment]
Please read the FAQ at http://benlo.com/esp8266/#faq
